ignores:
  [
    '@commitlint/*',
    '@nestjs/*',
    '@types/*',
    '@typescript-eslint/*',
    'commitizen',
    'depcheck',
    'eslint-*',
    'husky',
    'prettier-plugin-organize-imports',
    'source-map-support',
    'ts-loader',
    'tsconfig-paths',
    'prisma',
    '@prisma/client',
  ]
skip-missing: true
